alias status="git status"
alias push="git push"
alias pull="git pull"
alias add="git add"
alias commit="git commit -m"
alias log="git log | less"
alias cls="clear"


source ~/.bashrcapps

alias ff="    DISPLAY=:0 firefox &&     export XDG_RUNTIME_DIR=/data/data/com.termux/files/usr/tmp
    kill -9 $(pgrep -f "termux.x11") 2>/dev/null # Optional: Kill any existing X server process
    termux-x11 :0 >/dev/null &"
